owners = []
nickname = "frippy"
#nick_password = ""
alt_nicks = ["frippy_", "frippy__"]
realname = "frippy"
server = ""
#password = ""
port = 6697
use_ssl = true
#cert_path = "cert.der"
encoding = "UTF-8"
channels = ["#frippy"]
umodes = "+B"
user_info = "IRC Bot"
version = "frippy v0.5.1"
source = "https://github.com/Mavulp/frippy"
#ping_time = 180
#ping_timeout = 10
#burst_window_length = 8
#max_messages_in_burst = 15
#should_ghost = false
#ghost_sequence = []

#[channel_keys]
#"#frippy" = ""

[options]
#prefix = "."
#disabled_plugins = "Url"
# If no database url is set a HashMap is used
#mysql_url = "mysql://user:password@address/db"
# Both have to be set to load the ollama plugin
#ollama_url = "http://localhost:11434/api/generate"
#ollama_model = "tinyllama"
# If not set the URL plugin tries to find the title for all urls
#urls_whitelisted = "youtube\\.com,youtu\\.be"
# Converts messages from a bridge
#bridge_name = "bot"
# How username and message should be extracted - uses https://docs.rs/regex/ syntax
# Keep in mind that TOML expects backslashes to be escaped
#bridge_regex = "\\((?P<username>.*)\\) \u000f(?P<message>.*)$"
# Alternatively if the bridge uses IRCv3 relay nicks this can extract the username instead
#bridge_relay_format = "(?P<username>.+)/"
# Ignore messages that should not get parsed
#bridge_ignore_regex = " \\(edited\\)"
#bridge_remove_zws = "true"
